### ISSUE TITLE
License of the source code

### ISSUE THREAD

**Issue by Trilarion** [Ernir/robotron#1]
Hi,

I could not find any information about the license of the source code. Is it under GPL, MIT or something similar or rather all rights reserved?

Kind regards

**Comment by OddurV** [comment]
It looks like we picked "all rights reserved" when we posted this 9 years ago here: https://notendur.hi.is/~odv1/Robotron/#about
We must have forgotten to actually write that here on Github.

**Comment by Trilarion** [comment]
Thanks. That clarifies the license.
